version: '3.8'

services:
  workshop-user-api:
    image: costinelnegura/workshop-users-api:latest
    build:
      context: .
    environment:
      - MYSQL_HOST=host.docker.internal
      - MYSQL_PORT=3316
      - MYSQL_DATABASE=workshop_users_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=hfr6Y-34ApW-sP14J
      - EUREKA_SERVER_URI=http://host.docker.internal:8761/eureka
#      - ZIPKIN_SERVER_URI=http://host.docker.internal:9411
#      - RABBITMQ_SERVER_URI=amqp://guest:guest@host.docker.internal
#      - RABBITMQ_SERVER_HOST=host.docker.internal
#      - RABBITMQ_SERVER_PORT=5672
#      - RABBITMQ_SERVER_USERNAME=guest
#      - RABBITMQ_SERVER_PASSWORD=guest
#      - SPRING_ZIPKIN_SENDER_TYPE=rabbit
      - PORT=8085
    ports:
      - "8085:8085"
    networks:
      - workshop_network
networks:
  workshop_network:
    external: true