server:
  port: ${PORT:8080}

spring:
  application:
    name: workshop-users-api
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:workshop_db}
    username: ${MYSQL_USER:costinelnegura}
    password: ${MYSQL_PASSWORD:wytkyn-Kavmof-sipvo5}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: update
        format_sql: true
        enable_lazy_load_no_trans: true
        jdbc:
          lob:
            non_contextual_creation: true
        c3p0:
          min_size: 5
          max_size: 20
          timeout: 300
          max_statements: 50
          idle_test_period: 3000
          acquire_increment: 5
          validate: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: org.hibernate.dialect.MySQLDialect

app:
  jwt:
    secretKey: bjBLK4sad/HidJ+N/Iy8BeX5YsBGxQdM81GLQB6P+i4=

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URI:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
#  instance:
#    prefer-ip-address: true
#    hostname: ${HOSTNAME:localhost}

#spring:
#  zipkin:
#    base-url: ${ZIPKIN_SERVER_URI:http://localhost:9411}
#    sender:
#      type: ${SPRING_ZIPKIN_SENDER_TYPE:rabbit}
#  rabbitmq:
#    host: ${RABBITMQ_SERVER_HOST:localhost}
#    port: ${RABBITMQ_SERVER_PORT:5672}
#    username: ${RABBITMQ_SERVER_USER:guest}
#    password: ${RABBITMQ_SERVER_PASSWORD:guest}
#  sleuth:
#    sampler:
#      probability: 1

#logging:
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"
#  level:
#    springframework:
#      boot:
#        autoconfigure: DEBUG
#    web: DEBUG
#    root: DEBUG